<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add participant</title>
</head>
<body>
<h1>Add participant</h1>
<div>
    <form method="post">
        <label>Name</label>
        <input type="text" name="firstName" /><br>
        <label>LastName</label>
        <input type="text" name="lastName" /><br>
        <button type="submit">Добавить</button>
    </form>
</div>
</body>
</html>